### ISSUE TITLE
v1.1 breaks functionality.

### ISSUE THREAD

**Issue by Ynaught** [NiceKaleido/Warping-Wonders#1]
I can only speak on behalf of the mod version and have only been able to test with the clock. . . but the clock no longer works. Cannot confirm about horns or compass.

**Comment by Ynaught** [comment]
UPDATE:
I think the change disabled all features by default accidently and changed the settings you had prior when updating the mod. I used the settings function to enable it again and it works.

**Comment by NiceKaleido** [comment]
this happens when u update from previous versions. nothing I can do about. Thanks for reporting. If you got further issues or suggestions you'll get a quicker answer on our discord server.

**Comment by Ynaught** [comment]
I believe there is "something" you can do. If nothing else, you could make an "onload" chat message when the mod/datpack boots up to remind people to re-enable through the config command if they update versions. If it's possible to do onload to check if all states are disabled, you could do the chat prompt only if they are all disabled.

It's. . . just a bit silly that any user would feel the need to come here to figure out the pack auto-disables itself.

**Comment by Ynaught** [comment]
Ok, so it's a one time thing and not something for future updates. Forget I said anything then. The line "this happens when u update from previous versions" confused me regarding that aspect but the reply you just gave cleared things up completely. 😅
